apiVersion: v1
kind: Service
metadata:
  name: cidemo
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: cidemo
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cidemo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: cidemo
    spec:
      containers:
      - name: cidemo
        image: quay.io/jkbuster/cidemo:master
        ports:
        - containerPort: 80
